// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sistema_biblioteca.Data;

#nullable disable

namespace sistema_biblioteca.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20260521204849_CriarEstruturaCompletaBiblioteca")]
    partial class CriarEstruturaCompletaBiblioteca
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("sistema_biblioteca.Models.BloqueioSimple", b =>
                {
                    b.Property<int>("IdBloqueio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_BLOQUEIO");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("TEXT")
                        .HasColumnName("DATA_FIM");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("TEXT")
                        .HasColumnName("DATA_INICIO");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("MOTIVO");

                    b.HasKey("IdBloqueio");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Bloqueios");
                });

            modelBuilder.Entity("sistema_biblioteca.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPF")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("sistema_biblioteca.Models.DevolucaoSimple", b =>
                {
                    b.Property<int>("IdDevolucao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_DEVOLUCAO");

                    b.Property<DateTime?>("DataDevolucao")
                        .HasColumnType("TEXT")
                        .HasColumnName("DATA_DEVOLUCAO");

                    b.Property<int>("IdEmprestimo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_EMPRESTIMO");

                    b.HasKey("IdDevolucao");

                    b.HasIndex("IdEmprestimo");

                    b.ToTable("Devolucoes");
                });

            modelBuilder.Entity("sistema_biblioteca.Models.Emprestimo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataDevolucao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataPrevisaoDevolucao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataRetirada")
                        .HasColumnType("TEXT");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LivroId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("LivroId");

                    b.ToTable("Emprestimos");
                });

            modelBuilder.Entity("sistema_biblioteca.Models.EmprestimoSimple", b =>
                {
                    b.Property<int>("IdEmprestimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_EMPRESTIMO");

                    b.Property<DateTime?>("DataEmprestimo")
                        .HasColumnType("TEXT")
                        .HasColumnName("DATA_EMPRESTIMO");

                    b.Property<DateTime?>("DataPrevista")
                        .HasColumnType("TEXT")
                        .HasColumnName("DATA_PREVISTA");

                    b.Property<int>("IdExemplar")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_EXEMPLAR");

                    b.Property<int?>("IdFuncionario")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_FUNCIONARIO");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("STATUS");

                    b.HasKey("IdEmprestimo");

                    b.HasIndex("IdExemplar");

                    b.HasIndex("IdFuncionario");

                    b.HasIndex("IdUsuario");

                    b.ToTable("EmprestimosSql");
                });

            modelBuilder.Entity("sistema_biblioteca.Models.ExemplarSimple", b =>
                {
                    b.Property<int>("IdExemplar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_EXEMPLAR");

                    b.Property<string>("CodigoExemplar")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("CODIGO_EXEMPLAR");

                    b.Property<int>("IdLivro")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_LIVRO");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("STATUS");

                    b.HasKey("IdExemplar");

                    b.HasIndex("IdLivro");

                    b.ToTable("Exemplares");
                });

            modelBuilder.Entity("sistema_biblioteca.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPF")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("sistema_biblioteca.Models.FuncionarioSimple", b =>
                {
                    b.Property<int>("IdFuncionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_FUNCIONARIO");

                    b.Property<string>("Cargo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("CARGO");

                    b.Property<string>("Login")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("LOGIN");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("NOME");

                    b.Property<string>("Senha")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("SENHA");

                    b.HasKey("IdFuncionario");

                    b.ToTable("FuncionariosSql");
                });

            modelBuilder.Entity("sistema_biblioteca.Models.Livro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataPublicacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("QtdEstoque")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.HasIndex("Titulo", "Autor")
                        .IsUnique();

                    b.ToTable("Livros");
                });

            modelBuilder.Entity("sistema_biblioteca.Models.LivroSimple", b =>
                {
                    b.Property<int>("IdLivro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_LIVRO");

                    b.Property<int?>("Ano")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ANO");

                    b.Property<string>("Autor")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("AUTOR");

                    b.Property<string>("Editora")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("EDITORA");

                    b.Property<string>("Isbn")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("ISBN");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("TITULO");

                    b.HasKey("IdLivro");

                    b.ToTable("LivrosSql");
                });

            modelBuilder.Entity("sistema_biblioteca.Models.MultaSimple", b =>
                {
                    b.Property<int>("IdMulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_MULTA");

                    b.Property<int>("DiasAtraso")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DIAS_ATRASO");

                    b.Property<int>("IdEmprestimo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_EMPRESTIMO");

                    b.Property<string>("StatusPagamento")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("STATUS_PAGAMENTO");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT")
                        .HasColumnName("VALOR");

                    b.HasKey("IdMulta");

                    b.HasIndex("IdEmprestimo");

                    b.ToTable("Multas");
                });

            modelBuilder.Entity("sistema_biblioteca.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("Cpf")
                        .HasMaxLength(14)
                        .HasColumnType("TEXT")
                        .HasColumnName("CPF");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("TEXT")
                        .HasColumnName("DATA_CADASTRO");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("NOME");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("STATU");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("TELEFONE");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("sistema_biblioteca.Models.BloqueioSimple", b =>
                {
                    b.HasOne("sistema_biblioteca.Models.Usuario", "Usuario")
                        .WithMany("Bloqueios")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("sistema_biblioteca.Models.DevolucaoSimple", b =>
                {
                    b.HasOne("sistema_biblioteca.Models.EmprestimoSimple", "Emprestimo")
                        .WithMany("Devolucoes")
                        .HasForeignKey("IdEmprestimo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Emprestimo");
                });

            modelBuilder.Entity("sistema_biblioteca.Models.Emprestimo", b =>
                {
                    b.HasOne("sistema_biblioteca.Models.Cliente", "Cliente")
                        .WithMany("Emprestimos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sistema_biblioteca.Models.Funcionario", "Funcionario")
                        .WithMany("Emprestimos")
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sistema_biblioteca.Models.Livro", "Livro")
                        .WithMany("Emprestimos")
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Funcionario");

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("sistema_biblioteca.Models.EmprestimoSimple", b =>
                {
                    b.HasOne("sistema_biblioteca.Models.ExemplarSimple", "Exemplar")
                        .WithMany("Emprestimos")
                        .HasForeignKey("IdExemplar")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sistema_biblioteca.Models.FuncionarioSimple", "Funcionario")
                        .WithMany("Emprestimos")
                        .HasForeignKey("IdFuncionario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("sistema_biblioteca.Models.Usuario", "Usuario")
                        .WithMany("Emprestimos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exemplar");

                    b.Navigation("Funcionario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("sistema_biblioteca.Models.ExemplarSimple", b =>
                {
                    b.HasOne("sistema_biblioteca.Models.LivroSimple", "Livro")
                        .WithMany("Exemplares")
                        .HasForeignKey("IdLivro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("sistema_biblioteca.Models.MultaSimple", b =>
                {
                    b.HasOne("sistema_biblioteca.Models.EmprestimoSimple", "Emprestimo")
                        .WithMany("Multas")
                        .HasForeignKey("IdEmprestimo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Emprestimo");
                });

            modelBuilder.Entity("sistema_biblioteca.Models.Cliente", b =>
                {
                    b.Navigation("Emprestimos");
                });

            modelBuilder.Entity("sistema_biblioteca.Models.EmprestimoSimple", b =>
                {
                    b.Navigation("Devolucoes");

                    b.Navigation("Multas");
                });

            modelBuilder.Entity("sistema_biblioteca.Models.ExemplarSimple", b =>
                {
                    b.Navigation("Emprestimos");
                });

            modelBuilder.Entity("sistema_biblioteca.Models.Funcionario", b =>
                {
                    b.Navigation("Emprestimos");
                });

            modelBuilder.Entity("sistema_biblioteca.Models.FuncionarioSimple", b =>
                {
                    b.Navigation("Emprestimos");
                });

            modelBuilder.Entity("sistema_biblioteca.Models.Livro", b =>
                {
                    b.Navigation("Emprestimos");
                });

            modelBuilder.Entity("sistema_biblioteca.Models.LivroSimple", b =>
                {
                    b.Navigation("Exemplares");
                });

            modelBuilder.Entity("sistema_biblioteca.Models.Usuario", b =>
                {
                    b.Navigation("Bloqueios");

                    b.Navigation("Emprestimos");
                });
#pragma warning restore 612, 618
        }
    }
}
